version: '3.8'

services:
  # Backend service (Node.js server)
  backend:
    # Build the image using the Dockerfile in the ./server directory
    build:
      context: ./server # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile # Name of the Dockerfile (optional if named Dockerfile)
    container_name: kath-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  # Frontend service (Nginx)
  frontend:
    image: nginx:stable-alpine
    container_name: kath-frontend
    ports:
      - "5000:80"
    volumes:
      # Mount the built React app files into the Nginx HTML directory
      - ./client/dist:/usr/share/nginx/html:ro
      # Mount the custom Nginx configuration
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      # Wait for the backend service to be ready
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge # Use the default bridge driver
