# Docker Compose configuration version
version: '3.8'

# Define the services (containers)
services:
  # Backend service (Node.js server)
  backend:
    # Build the image using the Dockerfile in the ./server directory
    build:
      context: ./server # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile # Name of the Dockerfile (optional if named Dockerfile)
    container_name: myapp-backend # Optional: Custom container name
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network # Connect to the custom network

  # Frontend service (Nginx)
  frontend:
    # Use a standard Nginx image
    image: nginx:stable-alpine
    container_name: myapp-frontend # Optional: Custom container name
    ports:
      - "5000:80"
    volumes:
      # Mount the built React app files into the Nginx HTML directory
      # Assumes your build output is in client/dist
      - ./client/dist:/usr/share/nginx/html:ro # Mount as read-only
      # Mount the custom Nginx configuration
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount as read-only
    depends_on:
      # Wait for the backend service to be ready
      - backend
    restart: unless-stopped
    networks:
      - app-network # Connect to the custom network

# Define the network for services to communicate
networks:
  app-network:
    driver: bridge # Use the default bridge driver
